plugin: community.general.proxmox
validate_certs: false
want_facts: true
url: https://heartogold.local.deepthot.org:8006
compose:
  ansible_host: proxmox_agent_interfaces[1]["ip-addresses"][0].split('/')[0]
  ansible_user: ansible
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: "tag_"
cache: true
cache_plugin: memory
