---
- name: end role if no ipa needed
  meta: end_play
  when: "'tag_ipa' not in group_names"

#- wait_for: host="{{ansible_hostname}}" port=22 delay=5  timeout=300
#  name: Wait for "{{ansible_hostname}}" to boot

- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done;
  changed_when: false

- name: install required packages
  ansible.builtin.include_role: 
    name: packages
  vars:
    package:
      - emacs-nox
      - freeipa-client
      - autofs
      - nfs-kernel-server
      - nfs-common
      - direnv
      - qemu-guest-agent

- name: edit nsswitch to allow sss to access automount
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'automount:'
    line: "automount:\tfiles sss"

- hostname:
    name: "{{ ansible_hostname }}.local.deepthot.org"
    use: systemd

- timezone:
    name: America/Phoenix
  register: timezone

- name: restart cron
  systemd:
    name: cron
    daemon_reload: true
    enabled: true
    state: restarted
  when: timezone.changed

- name: join domain
  include_role:
    name: freeipa.ansible_freeipa.ipaclient

- name: Fix Automount
  include_tasks: fix_automount.yaml
